# Generated by Django 3.2.7 on 2021-10-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211021_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='dev_data',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='mon_data',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='obj_file',
            field=models.FileField(default=3, upload_to=''),
            preserve_default=False,
        ),
    ]
